USE ESTUDOS;
-- CRIAÇÃO DE TRIGGERS
-- GATILHO ACIONADO AO INCLUIR VENDA, DIMINUINDO UMA UNIDADE DO ESTOQUE
DELIMITER //
CREATE TRIGGER INCLUIR_VENDA AFTER UPDATE 
ON VENDAS
FOR EACH ROW 
BEGIN
    UPDATE ESTOQUE  SET QUANTIDADE_ESTOQUE = QUANTIDADE_ESTOQUE - (NEW.QUANTIDADE_VENDAS - OLD.QUANTIDADE_VENDAS)
    WHERE ID_ESTOQUE = 1;
END //
DELIMITER ;