USE ESTUDOS;
-- CRIAÇÃO DE PROCEDURE
-- INSERIR UMA NOVA CATEGORIA NO ESTOQUE
DELIMITER //
CREATE PROCEDURE PREENCHER(IN VNOME_CATEGORIA VARCHAR(150))

BEGIN
	DECLARE VID_CATEGORIA INT;
    
    INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES(VNOME_CATEGORIA);
    
    SET VID_CATEGORIA = (SELECT LAST_INSERT_ID());
    
    INSERT INTO ESTOQUE (ID_CATEGORIA, QUANTIDADE_ESTOQUE) VALUES(VID_CATEGORIA, 0);
    
    INSERT INTO VENDAS (ID_CATEGORIA, QUANTIDADE_VENDAS) VALUES(VID_CATEGORIA, 0);
END //
DELIMITER ;

-- INSERIR VENDA - ACRESCENTA VENDA
DELIMITER //
CREATE PROCEDURE INSERIR_VENDAS(IN VID_VENDAS INT)
BEGIN
	UPDATE VENDAS SET QUANTIDADE_VENDAS = QUANTIDADE_VENDAS + 1 WHERE ID_VENDAS = VID_VENDAS;
    SELECT
		CAT.ID_CATEGORIA AS "Código Categoria",
		CAT.NOME_CATEGORIA AS "Categoria",
		EST.QUANTIDADE_ESTOQUE AS "Estoque",
		VEN.QUANTIDADE_VENDAS AS "Vendas"
	FROM CATEGORIA CAT
	INNER JOIN ESTOQUE EST ON EST.ID_CATEGORIA = CAT.ID_CATEGORIA
	INNER JOIN VENDAS VEN ON VEN.ID_CATEGORIA = CAT.ID_CATEGORIA;
END //
DELIMITER ; 

-- INSERIR ESTOQUE - INSERE 1 ITEM NO ESTOQUE
DELIMITER //
CREATE PROCEDURE INSERIR_ESTOQUE(IN VID_ESTOQUE INT)
BEGIN
	UPDATE ESTOQUE SET QUANTIDADE_ESTOQUE = QUANTIDADE_ESTOQUE + 1 WHERE ID_ESTOQUE = VID_ESTOQUE;
    SELECT
		CAT.ID_CATEGORIA AS "Código Categoria",
		CAT.NOME_CATEGORIA AS "Categoria",
		EST.QUANTIDADE_ESTOQUE AS "Estoque",
		VEN.QUANTIDADE_VENDAS AS "Vendas"
	FROM CATEGORIA CAT
	INNER JOIN ESTOQUE EST ON EST.ID_CATEGORIA = CAT.ID_CATEGORIA
	INNER JOIN VENDAS VEN ON VEN.ID_CATEGORIA = CAT.ID_CATEGORIA;
END //
DELIMITER ;