DELIMITER // 
CREATE FUNCTION RETORNAR_DIFERENCA (VNOME_CATEGORIA VARCHAR(150))
RETURNS VARCHAR(100)
DETERMINISTIC
	BEGIN
		DECLARE VID_CATEGORIA INT;
        DECLARE VQT_ESTOQUE INT;
        DECLARE VQT_VENDAS INT;
        DECLARE DIFERENCA INT;
        DECLARE RESPOSTA VARCHAR(100);
        
        SET VID_CATEGORIA = (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOME_CATEGORIA = VNOME_CATEGORIA);
        SET VQT_ESTOQUE = (SELECT QUANTIDADE_ESTOQUE FROM ESTOQUE WHERE ID_CATEGORIA = VID_CATEGORIA);
        SET VQT_VENDAS = (SELECT QUANTIDADE_VENDAS FROM VENDAS WHERE ID_CATEGORIA = VID_CATEGORIA);
        
        SET DIFERENCA = VQT_ESTOQUE - VQT_VENDAS;
        
        IF DIFERENCA > 10 THEN
			SET RESPOSTA =  'SALDO CONFORTÁVEL!';
        ELSE
            SET RESPOSTA = 'SALDO PERIGOSO, ABASTEÇA EM BREVE!';
        END IF;
        RETURN (RESPOSTA);
    END // 
DELIMITER ;
