CREATE DATABASE ESTUDOS;
USE ESTUDOS;

-- Criação de Tabelas
CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(150)
);

CREATE TABLE ESTOQUE(
	ID_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CATEGORIA INT NOT NULL,
    QUANTIDADE_ESTOQUE INT DEFAULT 0,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE VENDAS(
	ID_VENDAS INT PRIMARY KEY AUTO_INCREMENT,
	ID_CATEGORIA INT NOT NULL,
    QUANTIDADE_VENDAS INT DEFAULT 0,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);













